{
 "title": "AstronometricsPy",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Word Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flask_request_counter_total{endpoint!~\"/words/.*|Match.*\"}",
     "legendFormat": "Word:{{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests Histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "Count by Seconds Bucket"
    }
   ]
  },
  {
   "title": "AstronometricsPy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "Requests Latency"
    }
   ]
  },
  {
   "title": "Endpoint Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flask_request_counter_total{endpoint=~\"/words.*\"}",
     "legendFormat": "{{endpoint}}-{{method}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "flask_gauge_metric", "legendFormat": "{{endpoint}}" }
   ]
  }
 ]
}